import React from 'react';

interface Props {
    /** A complete SVG document generated by our own renderers from validated numbers. */
    svg: string;
    className?: string;
    label: string;
}

const KolamSvg: React.FC<Props> = ({ svg, className = '', label }) => (
    <div role="img" aria-label={label} className={`[&_svg]:w-full [&_svg]:h-full ${className}`} dangerouslySetInnerHTML={{ __html: svg }} />
);

export default KolamSvg;
