import React from 'react';
import { Card } from './ui/Card';

const references = [
    {
        title: 'Array grammars and kolam',
        source: 'G. Siromoney, R. Siromoney & K. Krithivasan · Computer Graphics and Image Processing 3(1), 1974',
        summary: 'One of the first formal treatments of kolam: patterns described as picture languages generated by array grammars.',
    },
    {
        title: 'Reconstruction and extension of lost symmetries: examples from the Tamil of South India',
        source: 'P. Gerdes · Computers & Mathematics with Applications 17(4–6), 1989',
        summary: 'Models kolam strands as mirror curves around a dot grid. SOLVIX uses this model to recreate dot kolams and to join separate loops into a single line.',
    },
    {
        title: 'The Kolam Tradition',
        source: 'M. Ascher · American Scientist 90(1), 2002',
        summary: 'An accessible account of the cultural practice and the mathematics of kolam: symmetry, continuity and dot arrays.',
    },
    {
        title: 'KolamNetV2: efficient attention-based deep learning network for Tamil heritage art-kolam classification',
        source: 'npj Heritage Science, 2024',
        summary: 'A learned approach to kolam recognition, and a useful comparison for SOLVIX’s explainable geometric pipeline.',
    },
];

const Research: React.FC = () => (
    <section className="py-20 px-4 container mx-auto">
        <h2 className="font-heading text-4xl md:text-5xl text-center mb-12 gradient-text">Research & References</h2>
        <div className="max-w-4xl mx-auto space-y-6">
            {references.map(item => (
                <Card key={item.title}>
                    <h3 className="font-heading text-xl text-kaavi">{item.title}</h3>
                    <p className="text-sm text-muted italic my-2">{item.source}</p>
                    <p className="text-ink">{item.summary}</p>
                </Card>
            ))}
        </div>
    </section>
);

export default Research;
